disabled_rules:
    - type_name
    - todo

opt_in_rules:
    - anyobject_protocol
    - closure_spacing
    - collection_alignment
    - conditional_returns_on_newline
    - contains_over_first_not_nil
    - convenience_type    
    - empty_count
    - empty_string
    - empty_xctest_method
    - explicit_init
    - fatal_error_message
    - first_where
    - force_unwrapping        
    - last_where
    - literal_expression_end_indentation
    - modifier_order
    - multiline_arguments
    - multiline_function_chains
    - multiline_literal_brackets
    - multiline_parameters
    - operator_usage_whitespace
    - overridden_super_call
    - private_action
    - private_outlet    
    - toggle_bool
    - vertical_parameter_alignment_on_call
    - unused_capture_list
    - unused_import

cyclomatic_complexity:
    warning: 10
    error: 20

function_body_length:
    warning: 50
    error: 100

line_length:
    error: 120
    ignores_comments: true
    ignores_interpolated_strings: true
    ignores_function_declarations: false
    ignores_urls: true

identifier_name:
    max_length:
        warning: 40
        error: 60
    min_length:
        warning: 2
        error: 1

file_length:
    warning: 500
    error: 1000

nesting:
    type_level: 2

custom_rules:
    zero:

    final_class:
        name: "Final Class"
        regex: '(?<!final\s)class(?!\s(func|var))(?=[^\{\n]*[\{])'
        message: "Mark class as final. Or disable the rule."
        severity: error

    no_empty_space_after_logic:
        name: "Redundant Empty Space"
        regex: '(?<=\n)[ ]*?\n\s*?(?=\})'
        message: "Remove empty space before }."
        severity: warning
