disabled_rules:
    - type_name
    - todo  
    - force_unwrapping
    - force_try
    - force_cast
    - file_length
    - function_body_length
    - type_body_length
    - identifier_name
    - line_length

opt_in_rules:
    - anyobject_protocol
    - closure_spacing
    - collection_alignment
    - conditional_returns_on_newline
    - contains_over_first_not_nil
    - convenience_type    
    - empty_count
    - empty_string
    - empty_xctest_method
    - explicit_init
    - fatal_error_message
    - first_where      
    - last_where
    - literal_expression_end_indentation
    - modifier_order
    - multiline_arguments
    - multiline_function_chains
    - multiline_literal_brackets
    - multiline_parameters
    - operator_usage_whitespace
    - overridden_super_call
    - private_action
    - private_outlet    
    - toggle_bool
    - vertical_parameter_alignment_on_call
    - unused_capture_list
    - unused_import

cyclomatic_complexity:
    warning: 10
    error: 20

nesting:
    type_level: 2

custom_rules:
    zero:
        name: "Short .zero"
        regex: '\(top: 0, left: 0, bottom: 0, right: 0\)'
        message: "Please use short init `.zero`."
        severity: error

    self_reassignment:
        name: 'Self Backquote Reassignment'
        regex: '`self`'
        message: "Please replace `self` to self."
        severity: error

    marks_style:
        name: "Mark Style"
        regex: '// MARK:(?!\s-\s\w+?)'
        message: "Marks should follow the following structure: `// MARK: - Topic`."
        severity: warning

    cyrillic_in_comment:
        name: "Cyrillic Comment"
        regex: '/{2,}\s*?[а-яА-Я]+?'
        message: "Cyrillic comments are not allowed."
        severity: error

    comments_style:
        name: "Comment Style"
        regex: '^(\s*?(//\w+?))'
        message: "There should be a space after //"
        severity: warning

    final_class:
        name: "Final Class"
        regex: '(?<!final\s)class(?!\s(func|var))(?=[^\{\n]*[\{])'
        message: "Mark class as final. Or disable the rule."
        severity: error

    unowned_usage:
        name: "Unowned in Capture List"
        regex: '(?<=\{\s\[)(?:[\w\s\,]*?)unowned(?=[^\]]*?\])'
        message: "Use _weak_ keyword if you're not sure about property lifetime."
        severity: warning

    no_empty_space_after_logic:
        name: "Redundant Empty Space"
        regex: '(?<=\n)[ ]*?\n\s*?(?=\})'
        message: "Remove empty space before }."
        severity: warning

    fake_url_caution:
        name: "Fake URL Type Caution"
        regex: '[uU][rR][lL](?=\s?[:=]\s?String)'
        message: "Change variable type to URL. Or add String postfix: e.g. let urlString: String."
        severity: warning
        match_kinds: identifier

    no_empty_space_after_logic:
        name: "Redundant Empty Space"
        regex: '(?<=\n)[ ]*?\n\s*?(?=\})'
        message: "Remove empty space before }."
        severity: warning